### ISSUE TITLE
Question for adafruit_tft_lcd_st7789

### ISSUE THREAD

**Issue by webmiceleo** [SiliconLabs/third_party_hw_drivers_extension#2] opened 2024-02-22 20:11 UTC

**Comment by silabs-dmkozma** [comment] 2024-02-29 10:42
From the Community post:
https://community.silabs.com/s/question/0D5Vm000004L7mEKAS/3rdpartyhwdriversextension

I'm trying the 3rd party HW driver

https://github.com/SiliconLabs/third_party_hw_drivers_extension/tree/master/app/documentation/example/adafruit_tft_lcd_st7789

I build & flash the the example in BRD2703A & run the test as follows

cannot run the example as follow observations:

1 , Most of the time , Black screen .. reset button not work

2, the display can show basic color (white, red, green, blue, cyan, purple, yellow, orange, black) then Black screen

3, can finish the basic color, the screen display the words "HELLO WORLD", "Adafruit", "1.14" TFT". then Black Screen while show half of the words

4, Basic color done , display word done , inverting color done , 5 different image done , but Not drawing shapes then Black Screen .

I would like to ask is that any setting I missed or any other reason to make that happen ?

**Comment by silabs-ThanhNgo** [comment] 2024-03-04 03:42
Hello @webmiceleo  @silabs-dmkozma 

Thank for reporting the issue
Unfortunately, we were not able to reproduce the issue that you described
Could you export your project to SLS file, so we can build, flash and test it?

Thanks
assigned to @silabs-ThiepN

**Comment by webmiceleo** [comment] 2024-03-08 16:03
[adafruit_tft_lcd_st7789.sls.zip](https://github.com/SiliconLabs/third_party_hw_drivers_extension/files/14540330/adafruit_tft_lcd_st7789.sls.zip)

**Comment by silabs-ThiepN** [comment] 2024-03-09 07:08
Hi @webmiceleo @silabs-dmkozma,
Thank for reporting the issue. We found an issue related to the toolchain version that affects the functionality of some functions. We fixed it and it has been released in version [2.0.0](https://github.com/SiliconLabs/third_party_hw_drivers_extension/releases/tag/v2.0.0). Please update to the new version and try again.
![v2 0 0](https://github.com/SiliconLabs/third_party_hw_drivers_extension/assets/129280966/e5c15f03-31e6-4145-9303-eee327cd854b)

**Closed as completed** 2024-04-03 13:34 UTC
